import { describe, expect, it } from 'vitest'
import {
  normalizeMarkdownStrongWhitespace,
  renderMarkdownToSafeHtml,
  sanitizeContentHtml,
  sanitizeInternalContentHtml,
} from './markdown-compatibility'

describe('sanitizeContentHtml', () => {
  it('removes workspace-covering layout declarations while preserving article typography', () => {
    const html = sanitizeContentHtml(`
      <style>.app { display: none }</style>
      <p style="position: fixed; inset: 0; z-index: 2147483647; transform: scale(50); color: #123456; text-align: center; margin: 1em">
        正常正文
      </p>
      <p style="position: sticky; top: 0">置顶正文</p>
    `)
    const document = new DOMParser().parseFromString(html, 'text/html')
    const paragraph = document.querySelector('p')

    expect(document.querySelector('style')).toBeNull()
    expect(paragraph?.style.position).toBe('')
    expect(paragraph?.style.zIndex).toBe('')
    expect(paragraph?.style.inset).toBe('')
    expect(paragraph?.style.transform).toBe('')
    expect(paragraph?.style.color).toBe('rgb(18, 52, 86)')
    expect(paragraph?.style.textAlign).toBe('center')
    expect(paragraph?.style.margin).toBe('1em')
    expect(document.querySelectorAll('p')[1]?.style.position).toBe('')
    expect(document.querySelectorAll('p')[1]?.style.top).toBe('')
  })

  it('removes request-capable CSS values while retaining safe backgrounds', () => {
    const html = sanitizeContentHtml(`
      <p style="background: #f5f7f9">安全背景</p>
      <p style="background-image: url('https://example.test/tracker.png'); list-style: url('https://example.test/marker.png')">危险背景</p>
      <p style="background: u\\72l('https://example.test/escaped.png'); color: #123456">转义网络值</p>
    `)
    const paragraphs = new DOMParser().parseFromString(html, 'text/html').querySelectorAll('p')

    expect(paragraphs[0]?.style.background).toBe('rgb(245, 247, 249)')
    expect(paragraphs[1]?.style.backgroundImage).toBe('')
    expect(paragraphs[1]?.style.listStyle).toBe('')
    expect(paragraphs[2]?.style.background).toBe('')
    expect(paragraphs[2]?.style.color).toBe('rgb(18, 52, 86)')
    expect(html).not.toContain('escaped.png')
  })

  it('removes request-capable image alternatives and untrusted application protocol attributes', () => {
    const html = sanitizeContentHtml(`
      <img
        src="https://example.test/fallback.png"
        srcset="https://example.test/tracker.png 2x"
        data-missing-image-action="replace"
        data-edit-target="title"
        data-untrusted="value"
        alt="正文配图"
      >
    `)
    const image = new DOMParser().parseFromString(html, 'text/html').querySelector('img')

    expect(image?.getAttribute('src')).toBe('https://example.test/fallback.png')
    expect(image?.getAttribute('alt')).toBe('正文配图')
    expect(image?.hasAttribute('srcset')).toBe(false)
    expect(image?.hasAttribute('data-missing-image-action')).toBe(false)
    expect(image?.hasAttribute('data-edit-target')).toBe(false)
    expect(image?.hasAttribute('data-untrusted')).toBe(false)
  })

  it('removes automatic media requests and legacy request-capable attributes', () => {
    const html = sanitizeContentHtml(`
      <table background="https://example.test/tracker.png"><tr><td>正常表格</td></tr></table>
      <video autoplay preload="auto" poster="https://example.test/poster.png" src="https://example.test/video.mp4"><track src="https://example.test/captions.vtt"></video>
      <audio autoplay src="https://example.test/audio.mp3"><source src="https://example.test/audio.ogg"></audio>
      <img src="https://example.test/allowed-image.png" background="https://example.test/legacy.png" alt="正常配图">
      <input type="image" src="https://example.test/input.png">
      <a href="https://example.test/article" ping="https://example.test/ping">正常链接</a>
    `)
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.querySelector('table')?.hasAttribute('background')).toBe(false)
    expect(document.querySelector('video, audio, source, track')).toBeNull()
    expect(document.querySelector('input, button, select, textarea')).toBeNull()
    expect(document.querySelector('img')?.getAttribute('src')).toBe('https://example.test/allowed-image.png')
    expect(document.querySelector('img')?.hasAttribute('background')).toBe(false)
    expect(document.querySelector('a')?.hasAttribute('ping')).toBe(false)
  })

  it('keeps the non-interactive content markers generated by the application', () => {
    const html = sanitizeContentHtml(`
      <aside data-callout="warning" data-callout-title="先备份" data-callout-fold="collapsed">
        <div data-callout-title="">先备份</div>
        <div data-callout-content=""><p>正文</p></div>
      </aside>
      <ul data-type="taskList"><li data-type="taskItem" data-checked="true">完成</li></ul>
      <div data-source-spacer="true" style="height: 1.72em; min-height: 1.72em; display: block"></div>
    `)
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.querySelector('aside')?.dataset).toMatchObject({
      callout: 'warning',
      calloutTitle: '先备份',
      calloutFold: 'collapsed',
    })
    expect(document.querySelector('[data-callout-content]')).not.toBeNull()
    expect(document.querySelector('li')?.dataset).toMatchObject({ type: 'taskItem', checked: 'true' })
    expect(document.querySelector('[data-source-spacer]')?.getAttribute('style')).toContain('height: 1.72em')
  })

  it('only preserves missing-image state through the explicit internal sanitizer', () => {
    const forged = '<img src="https://example.test/image.png" data-missing-id="forged" data-missing-asset="secrets.png">'
    const external = new DOMParser().parseFromString(sanitizeContentHtml(forged), 'text/html').querySelector('img')
    const internal = new DOMParser().parseFromString(sanitizeInternalContentHtml(forged), 'text/html').querySelector('img')

    expect(external?.hasAttribute('data-missing-id')).toBe(false)
    expect(external?.hasAttribute('data-missing-asset')).toBe(false)
    expect(internal?.dataset).toMatchObject({ missingId: 'forged', missingAsset: 'secrets.png' })
  })
})

describe('renderMarkdownToSafeHtml', () => {
  it('repairs whitespace placed after an opening strong marker', () => {
    const markdown = [
      '支持** 100 万 Token 上下文**，也支持正常的 **标准粗体**。',
      '- ** 列表中的粗体**',
      '** 行首粗体**',
    ].join('\n')
    const html = renderMarkdownToSafeHtml(markdown)
    const document = new DOMParser().parseFromString(html, 'text/html')
    const strong = document.querySelectorAll('strong')

    expect(strong).toHaveLength(4)
    expect(strong[0]?.textContent).toBe('100 万 Token 上下文')
    expect(strong[1]?.textContent).toBe('标准粗体')
    expect(strong[2]?.textContent).toBe('列表中的粗体')
    expect(strong[3]?.textContent).toBe('行首粗体')
    expect(document.querySelector('p')?.textContent).toBe('支持 100 万 Token 上下文，也支持正常的 标准粗体。')
  })

  it('repairs whitespace placed before a closing strong marker', () => {
    const markdown = [
      '- **问题选择： **判断哪个问题值得解决；',
      '- **领域理解：  ** 理解行业规则和现场语境；',
    ].join('\n')
    const html = renderMarkdownToSafeHtml(markdown)
    const document = new DOMParser().parseFromString(html, 'text/html')
    const items = document.querySelectorAll('li')

    expect(items[0].innerHTML).toBe('<strong>问题选择：</strong> 判断哪个问题值得解决；')
    expect(items[1].innerHTML).toBe('<strong>领域理解：</strong> 理解行业规则和现场语境；')
  })

  it('does not repair strong-like text inside inline or fenced code', () => {
    const markdown = ['`** 保留空格 **`', '', '```md', '** 保留空格 **', '```'].join('\n')

    expect(normalizeMarkdownStrongWhitespace(markdown)).toBe(markdown)
  })

  it('does not reinterpret escaped strong markers', () => {
    const markdown = String.raw`\** 保留空格 **`

    expect(normalizeMarkdownStrongWhitespace(markdown)).toBe(markdown)
  })

  it('converts Obsidian callouts into semantic editable containers', () => {
    const html = renderMarkdownToSafeHtml([
      '> [!warning] 先备份，再接入同步',
      '> 第一次配置时，先选一台设备作为主设备。',
      '>',
      '> 复制整个 Vault 文件夹作为备份。',
    ].join('\n'))

    const document = new DOMParser().parseFromString(html, 'text/html')
    const callout = document.querySelector('aside[data-callout="warning"]')

    expect(callout?.getAttribute('data-callout-title')).toBe('先备份，再接入同步')
    expect(callout?.querySelector('[data-callout-title]')?.textContent).toBe('先备份，再接入同步')
    expect(callout?.querySelector('[data-callout-content]')?.textContent).toContain('第一次配置时')
    expect(callout?.querySelectorAll('[data-callout-content] p')).toHaveLength(2)
    expect(html).not.toContain('[!warning]')
  })

  it('normalizes callout aliases and preserves fold state', () => {
    const html = renderMarkdownToSafeHtml('> [!abstract]- 本文摘要\n> 摘要正文')
    const document = new DOMParser().parseFromString(html, 'text/html')
    const callout = document.querySelector('aside')

    expect(callout?.dataset.callout).toBe('summary')
    expect(callout?.dataset.calloutFold).toBe('collapsed')
  })

  it('keeps GFM task lists editable instead of flattening their checkboxes', () => {
    const html = renderMarkdownToSafeHtml('- [x] 已完成\n- [ ] 待处理')
    const document = new DOMParser().parseFromString(html, 'text/html')
    const items = document.querySelectorAll('li[data-type="taskItem"]')

    expect(document.querySelector('ul[data-type="taskList"]')).not.toBeNull()
    expect(items).toHaveLength(2)
    expect(items[0].getAttribute('data-checked')).toBe('true')
    expect(items[1].getAttribute('data-checked')).toBe('false')
    expect(document.querySelector('input')).toBeNull()
  })

  it('supports common Obsidian inline syntax without exposing vault-only markup', () => {
    const html = renderMarkdownToSafeHtml('#### 小标题\n\n==重点==、[[说明页|查看说明]]。%%内部备注%%')

    expect(html).toContain('<h4>小标题</h4>')
    expect(html).toContain('<mark>重点</mark>')
    expect(html).toContain('查看说明')
    expect(html).not.toContain('[[')
    expect(html).not.toContain('内部备注')
  })

  it('renders referenced Markdown footnotes with inline formatting and stable numbering', () => {
    const html = renderMarkdownToSafeHtml([
      '正文先引用脚注[^note]，稍后再次引用[^note]，并补充第二条[^2]。',
      '',
      '[^note]: 支持 **加粗** 与 `行内代码`。',
      '[^2]: 第二条说明',
      '    可以跨行书写。',
    ].join('\n'))
    const document = new DOMParser().parseFromString(html, 'text/html')
    const references = document.querySelectorAll('sup[data-footnote-reference]')
    const notes = document.querySelectorAll('[data-footnote-item]')

    expect(references).toHaveLength(3)
    expect(Array.from(references).map(reference => reference.textContent)).toEqual(['1', '1', '2'])
    expect(notes).toHaveLength(2)
    expect(notes[0]?.id).toBe('ez-footnote-1')
    expect(notes[0]?.querySelector('strong')?.textContent).toBe('加粗')
    expect(notes[0]?.querySelector('code')?.textContent).toBe('行内代码')
    expect(notes[1]?.textContent).toContain('第二条说明')
    expect(notes[1]?.textContent).toContain('可以跨行书写')
  })

  it('keeps unknown footnote references literal and sanitizes definition HTML', () => {
    const html = renderMarkdownToSafeHtml([
      '未知引用[^missing]，有效引用[^safe]。',
      '',
      '[^safe]: 安全正文<script>alert(1)</script><img src="x" onerror="alert(2)">',
    ].join('\n'))
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.body.textContent).toContain('[^missing]')
    expect(document.querySelectorAll('[data-footnote-item]')).toHaveLength(1)
    expect(html).not.toContain('<script')
    expect(html).not.toContain('onerror')
  })

  it('does not turn footnote-like text inside code into references', () => {
    const html = renderMarkdownToSafeHtml([
      '有效引用[^note]，代码中保留 `[^note]`。',
      '',
      '```md',
      '[^note]',
      '```',
      '',
      '[^note]: 正常脚注',
    ].join('\n'))
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.querySelectorAll('sup[data-footnote-reference]')).toHaveLength(1)
    expect(document.querySelector('p code')?.textContent).toBe('[^note]')
    expect(document.querySelector('pre')?.textContent).toContain('[^note]')
  })

  it('sanitizes unsafe HTML embedded in Markdown', () => {
    const html = renderMarkdownToSafeHtml('正文<script>alert(1)</script><img src="x" onerror="alert(2)" data-missing-id="forged" data-missing-asset="secrets.png"><video autoplay src="https://example.test/video.mp4"></video>')

    expect(html).not.toContain('<script')
    expect(html).not.toContain('onerror')
    expect(html).not.toContain('data-missing-id')
    expect(html).not.toContain('data-missing-asset')
    expect(html).not.toContain('<video')
  })

  it('preserves extra top-level Markdown blank lines as visible spacers', () => {
    const html = renderMarkdownToSafeHtml('第一段\n\n\n\n第二段')
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.querySelectorAll('[data-source-spacer="true"]')).toHaveLength(2)
    expect(document.querySelector('[data-source-spacer]')?.getAttribute('style')).toContain('height: 1.72em')
    expect(document.body.textContent).toContain('第一段')
    expect(document.body.textContent).toContain('第二段')
  })

  it('keeps one structural blank line invisible and does not alter fenced code spacing', () => {
    const html = renderMarkdownToSafeHtml('第一段\n\n第二段\n\n```text\n第一行\n\n\n第三行\n```')
    const document = new DOMParser().parseFromString(html, 'text/html')

    expect(document.querySelector('[data-source-spacer]')).toBeNull()
    expect(document.querySelector('pre')?.textContent).toContain('第一行\n\n\n第三行')
  })
})
