import { expect, test } from '@playwright/test'
import { editTitle } from './workbench-helpers'

const gif = 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
const openLibrary = async (page: import('@playwright/test').Page) => {
  if (await page.getByRole('button', { name: '模板素材库', exact: true }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: '模板素材库', exact: true }).click()
  await expect(page.locator('.template-library')).toHaveAttribute('aria-busy', 'false')
}

test('collects selected Markdown, inserts it in another draft, and preserves undo and reload', async ({ page }, info) => {
  await page.goto('/')
  const sentence = '**这句话值得反复使用**，保留原有格式。'
  await page.locator('input[accept*=".md"]').setInputFiles({ name: 'collect.md', mimeType: 'text/markdown', buffer: Buffer.from(`# 收藏测试\n\n${sentence}\n\n原文的下一段。`) })
  const line = page.locator('.cm-line').filter({ hasText: '这句话值得反复使用' })
  await line.click()
  await page.keyboard.press('Home')
  await page.keyboard.press('Shift+End')
  await page.getByRole('button', { name: '收藏到模板库', exact: true }).click()
  await expect(page.getByLabel('模板内容', { exact: true })).toHaveValue(sentence)
  await page.getByLabel('素材名称', { exact: true }).fill('常用金句')
  await page.getByLabel('素材分类', { exact: true }).fill('金句')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await expect(page.locator('.library-notice')).toContainText('素材已保存')
  await page.screenshot({ path: info.outputPath('collected-text.png') })
  await page.getByRole('button', { name: '关闭模板素材库', exact: true }).click()
  await expect(page.locator('.wechat-content')).toContainText('原文的下一段。')
  await page.getByRole('button', { name: '新建文档', exact: true }).click()
  await page.getByRole('button', { name: '空白文档', exact: true }).click()
  await editTitle(page, '另一篇文章')
  await page.locator('.cm-content').press('Control+End')
  await openLibrary(page)
  await page.getByRole('button', { name: '添加到编辑器：常用金句', exact: true }).click()
  await expect(page.locator('.wechat-content strong')).toContainText('这句话值得反复使用')
  await expect(page.locator('.topbar-document-title')).toHaveText('另一篇文章')
  await page.locator('.source-toolbar').getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.locator('.wechat-content')).not.toContainText('这句话值得反复使用')
  await expect(page.locator('.topbar-document-title')).toHaveText('另一篇文章')
  await page.locator('.source-toolbar').getByRole('button', { name: '重做', exact: true }).click()
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  await page.reload()
  await expect(page.locator('.wechat-content strong')).toContainText('这句话值得反复使用')
  await openLibrary(page)
  await expect(page.locator('.library-card')).toHaveCount(1)
})

test('creates and edits text templates, filters categories, and protects unsaved changes', async ({ page }, info) => {
  await page.goto('/')
  await openLibrary(page)
  await page.locator('.library-create-actions summary').click()
  await page.getByRole('button', { name: '新建文字模板', exact: true }).click()
  await page.getByLabel('素材名称', { exact: true }).fill('文章结构')
  await page.getByLabel('模板内容', { exact: true }).fill(' ')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('模板内容不能为空')
  await page.getByLabel('模板内容', { exact: true }).fill('## 开头\n\n正文\n\n## 结尾')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '关闭模板素材库', exact: true }).click()
  await expect(page.getByLabel('模板内容', { exact: true })).toHaveValue('## 开头\n\n正文\n\n## 结尾')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await expect(page.getByRole('button', { name: '添加到编辑器：文章结构', exact: true })).toBeDisabled()
  await page.locator('.library-card').hover()
  await page.getByRole('button', { name: '编辑素材：文章结构', exact: true }).click()
  await page.getByLabel('素材分类', { exact: true }).fill('长文结构')
  await page.getByLabel('模板内容', { exact: true }).fill('## 开场\n\n先写结论\n\n## 总结')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await page.locator('.library-filter-menu summary').click()
  await page.getByLabel('筛选素材分类').selectOption({ label: '长文结构' })
  await page.locator('.library-filter-menu summary').click()
  await expect(page.locator('.library-card')).toHaveCount(1)
  await page.getByLabel('搜索素材').fill('不存在的内容')
  await expect(page.locator('.library-empty')).toContainText('没有找到匹配')
  await page.getByLabel('搜索素材').fill('先写结论')
  await expect(page.locator('.library-card')).toHaveCount(1)
  await page.setViewportSize({ width: 320, height: 844 })
  expect(await page.locator('.template-library-sidebar').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('library-mobile.png') })
  await page.locator('.library-card').hover()
  await page.getByRole('button', { name: '编辑素材：文章结构', exact: true }).click()
  await expect(page.getByLabel('模板内容', { exact: true })).toHaveValue('## 开场\n\n先写结论\n\n## 总结')
  expect(await page.locator('.template-library-sidebar').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
})

test('uploads and categorizes images, inserts an independent copy, and retains it after library deletion', async ({ page }, info) => {
  await page.goto('/')
  await page.getByRole('button', { name: '开始写稿' }).click()
  await editTitle(page, '图片复用')
  await page.locator('.cm-content').press('Control+Home')
  await openLibrary(page)
  await page.locator('.template-library input[type=file]').setInputFiles([
    { name: '常用表情.gif', mimeType: 'image/gif', buffer: Buffer.from(gif, 'base64') },
    { name: '品牌图.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect width="120" height="80" fill="#1648ff"/></svg>') },
  ])
  await page.getByLabel('素材分类', { exact: true }).fill('日常配图')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await expect(page.locator('.library-card')).toHaveCount(2)
  const row = await page.locator('.library-card').first().boundingBox()
  expect(row!.height).toBeGreaterThanOrEqual(70)
  expect(row!.height).toBeLessThanOrEqual(90)
  expect((await page.locator('.template-library-sidebar').boundingBox())!.width).toBe(280)
  await page.screenshot({ path: info.outputPath('library-images.png') })
  await page.getByRole('button', { name: '关闭模板素材库', exact: true }).click()
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  await page.reload()
  await expect(page.locator('.topbar-document-title')).toHaveText('图片复用')
  await openLibrary(page)
  await expect(page.locator('.library-card img')).toHaveCount(2)
  await page.locator('.library-filter-menu summary').click()
  await page.getByLabel('筛选素材分类').selectOption({ label: '日常配图' })
  await page.locator('.library-filter-menu summary').click()
  await page.getByRole('button', { name: '添加到编辑器：常用表情.gif', exact: true }).click()
  await expect(page.locator('.source-image-widget')).toBeVisible()
  await expect(page.locator('.topbar-document-title')).toHaveText('图片复用')
  await expect(page.locator('.wechat-content img')).toHaveCount(1)
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  await openLibrary(page)
  await page.locator('.library-card').filter({ hasText: '常用表情.gif' }).hover()
  await page.getByRole('button', { name: '删除素材：常用表情.gif', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.locator('.library-card')).toHaveCount(1)
  await page.getByRole('button', { name: '关闭模板素材库', exact: true }).click()
  await page.reload()
  await expect(page.locator('.source-image-widget')).toBeVisible()
  await expect(page.locator('.wechat-content img')).toHaveCount(1)
  expect(await page.locator('.wechat-content img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
})

test('rejects a damaged image batch without saving any of it', async ({ page }) => {
  await page.goto('/')
  await openLibrary(page)
  await page.locator('.template-library input[type=file]').setInputFiles([
    { name: 'valid.gif', mimeType: 'image/gif', buffer: Buffer.from(gif, 'base64') },
    { name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('not an image') },
  ])
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('broken.png')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '返回素材库', exact: true }).click()
  await expect(page.locator('.library-card')).toHaveCount(0)
})

test('inserts a sanitized HTML template over the selected body text', async ({ page }) => {
  await page.goto('/')
  await page.locator('input[accept*=".md"]').setInputFiles({ name: 'replace.md', mimeType: 'text/markdown', buffer: Buffer.from('# 保留标题\n\n替换这一段\n\n保留下一段') })
  await page.locator('.cm-line').filter({ hasText: '替换这一段' }).click()
  await page.keyboard.press('Home')
  await page.keyboard.press('Shift+End')
  await openLibrary(page)
  await page.locator('.library-create-actions summary').click()
  await page.getByRole('button', { name: '新建文字模板', exact: true }).click()
  await page.getByLabel('素材名称', { exact: true }).fill('HTML 结尾')
  await page.getByRole('combobox', { name: '内容格式' }).selectOption('html')
  await page.getByLabel('模板内容', { exact: true }).fill('<p><strong>新的结尾</strong></p><script>window.libraryInjected = true</script>')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  await page.getByRole('button', { name: '添加到编辑器：HTML 结尾', exact: true }).click()
  await expect(page.locator('.wechat-content strong')).toHaveText('新的结尾')
  await expect(page.locator('.wechat-content')).not.toContainText('替换这一段')
  await expect(page.locator('.wechat-content')).toContainText('保留下一段')
  await expect(page.locator('.topbar-document-title')).toHaveText('保留标题')
  expect(await page.evaluate(() => 'libraryInjected' in window)).toBe(false)
  await page.locator('.source-toolbar').getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.locator('.wechat-content')).toContainText('替换这一段')
})

test('keeps the editor usable beside the library, drops at the pointer, and collapses from the rail', async ({ page }, info) => {
  await page.goto('/')
  await page.locator('input[accept*=".md"]').setInputFiles({ name: 'drop.md', mimeType: 'text/markdown', buffer: Buffer.from('# 拖拽测试\n\n第一段保留\n\n目标位置\n\n末段保留') })
  await openLibrary(page)
  await expect(page.getByRole('dialog', { name: '模板素材库' })).toHaveCount(0)
  const sidebar = page.getByRole('complementary', { name: '模板素材库' })
  expect(await page.locator('.workbench-toolbar').evaluate(node => node.getBoundingClientRect().right)).toBeLessThanOrEqual(1440)
  expect(await page.locator('.preview-lane').evaluate(node => node.getBoundingClientRect().right)).toBeLessThanOrEqual(1440)
  const body = page.locator('.cm-line').filter({ hasText: '目标位置' })
  await body.click()
  await page.keyboard.press('End')
  await page.keyboard.insertText('继续编辑')
  await expect(page.locator('.wechat-content')).toContainText('目标位置继续编辑')
  await page.locator('.template-library input[type=file]').setInputFiles({ name: '拖拽图.gif', mimeType: 'image/gif', buffer: Buffer.from(gif, 'base64') })
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  const card = page.locator('.library-card').filter({ hasText: '拖拽图.gif' })
  await expect(card).toBeVisible()
  // Keep the old cursor on the last paragraph; the drop must use the pointer instead.
  await page.locator('.cm-content').press('Control+End')
  await card.locator('.library-card-preview').dragTo(body, { targetPosition: { x: 2, y: 10 } })
  await expect(page.locator('.source-image-widget')).toHaveCount(1)
  await expect(sidebar).toBeVisible()
  await expect(page.locator('.wechat-content img')).toHaveCount(1)
  const blocks = await page.locator('.wechat-content').evaluate(node => Array.from(node.querySelectorAll('p, img')).map(child => child.tagName === 'IMG' ? 'IMAGE' : child.textContent))
  expect(blocks.indexOf('IMAGE')).toBeGreaterThan(blocks.findIndex(text => text?.includes('第一段保留')))
  expect(blocks.indexOf('IMAGE')).toBeLessThan(blocks.findIndex(text => text?.includes('目标位置继续编辑')))
  await page.screenshot({ path: info.outputPath('library-sidebar-desktop.png') })
  await page.locator('.source-toolbar').getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.locator('.source-image-widget')).toHaveCount(0)
  await expect(page.locator('.wechat-content')).toContainText('目标位置继续编辑')
  await body.click()
  await page.keyboard.press('Home')
  await page.keyboard.press('Shift+End')
  const collect = page.getByRole('button', { name: '收藏到模板库', exact: true })
  await expect(collect).toHaveText('')
  await expect(collect).toHaveAttribute('title', '收藏到模板库')
  await collect.click()
  await expect(page.getByLabel('模板内容', { exact: true })).toHaveValue('目标位置继续编辑')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '模板素材库', exact: true }).click()
  await expect(sidebar).toBeVisible()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '新建文档', exact: true }).click()
  await expect(page.getByLabel('模板内容', { exact: true })).toHaveValue('目标位置继续编辑')
  await page.getByRole('button', { name: '保存到素材库', exact: true }).click()
  const textCard = page.locator('.library-card.text')
  const lastLine = page.locator('.cm-line').filter({ hasText: '末段保留' })
  await textCard.locator('.library-card-preview').dragTo(lastLine, { targetPosition: { x: 2, y: 10 } })
  await expect(page.locator('.wechat-content')).toContainText('目标位置继续编辑末段保留')
  await expect(sidebar).toBeVisible()
  await page.locator('.source-toolbar').getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.locator('.wechat-content')).not.toContainText('目标位置继续编辑末段保留')
  await page.setViewportSize({ width: 1000, height: 900 })
  const paper = await page.locator('.paper-panel').boundingBox()
  const library = await sidebar.boundingBox()
  expect(library!.x).toBe(72)
  expect(library!.x + library!.width).toBeLessThanOrEqual(paper!.x)
  expect(paper!.x + paper!.width).toBeLessThanOrEqual(1000)
  await page.setViewportSize({ width: 390, height: 844 })
  const mobilePaper = await page.locator('.paper-panel').boundingBox()
  const mobileLibrary = await sidebar.boundingBox()
  expect(mobilePaper!.y + mobilePaper!.height).toBeLessThanOrEqual(mobileLibrary!.y + 1)
  await page.screenshot({ path: info.outputPath('library-sidebar-mobile.png') })
  await page.getByRole('button', { name: '模板素材库', exact: true }).click()
  await expect(sidebar).toHaveCount(0)
  await expect(page.getByRole('button', { name: '模板素材库', exact: true })).toBeFocused()
  await openLibrary(page)
  await page.keyboard.press('Escape')
  await expect(sidebar).toHaveCount(0)
})
