import { expect, test } from '@playwright/test'

test('uses a compact inspector with exclusive tabs, instant themes, resizing and collapse', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1674, height: 1000 })
  await page.goto('/')
  await page.getByRole('button', { name: '使用公众号长文模板开始' }).click()
  await page.locator('.preview-settings-toggle').click()
  const panel = page.getByRole('dialog', { name: '公众号排版设置', exact: true })
  const tabs = panel.getByRole('tablist', { name: '公众号设置模块' })
  await expect.poll(async () => (await panel.boundingBox())!.width).toBe(310)
  await expect(panel.getByRole('tabpanel')).toHaveCount(1)
  const card = panel.locator('.wechat-theme-card').first()
  expect((await card.boundingBox())!.height).toBeLessThan(100)
  await expect(panel.locator('input[name="source-style-policy"]')).toHaveCount(0)
  await panel.getByRole('button', { name: /^应用克莱因蓝主题/ }).click()
  await expect(page.locator('.wechat-content [data-wechat-theme="klein"]')).toHaveCount(1)
  await expect(panel.getByRole('button', { name: /^应用克莱因蓝主题/ })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: testInfo.outputPath('wechat-inspector-desktop.png'), animations: 'disabled' })
  await tabs.getByRole('tab', { name: '主题', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(tabs.getByRole('tab', { name: '样式', exact: true })).toBeFocused()
  await expect(panel.getByRole('tabpanel')).toHaveCount(1)
  await panel.getByRole('radio', { name: '宋体', exact: true }).click()
  await expect(panel.getByRole('radio', { name: '宋体', exact: true })).toHaveAttribute('aria-checked', 'true')
  await tabs.getByRole('tab', { name: '样式', exact: true }).click()
  await expect(panel.getByRole('button', { name: '重置配色' })).toBeVisible()
  await tabs.getByRole('tab', { name: '样式', exact: true }).click()
  await panel.getByRole('radio', { name: '宽松', exact: true }).click()
  await expect(panel.getByRole('radio', { name: '宽松', exact: true })).toHaveAttribute('aria-checked', 'true')
  const resizer = page.getByRole('separator', { name: '调整公众号主题侧栏宽度' })
  const bounds = (await resizer.boundingBox())!
  expect(Math.abs(bounds.x + bounds.width - (await panel.boundingBox())!.x)).toBeLessThan(1)
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + 120)
  await page.mouse.down()
  await page.mouse.move(bounds.x - 40, bounds.y + 120, { steps: 5 })
  await page.mouse.up()
  const resizedWidth = (await panel.boundingBox())!.width
  expect(resizedWidth).toBeGreaterThan(340)
  await resizer.focus()
  await page.keyboard.press('ArrowRight')
  await expect.poll(async () => (await panel.boundingBox())!.width).toBeCloseTo(resizedWidth - 16, 0)
  await page.keyboard.press('Home')
  await expect(panel).toBeHidden()
  await expect(page.locator('.preview-settings-toggle')).toBeFocused()
  await page.locator('.preview-settings-toggle').click()
  await expect(tabs.getByRole('tab', { name: '样式', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Escape')
  await expect(page.locator('.preview-settings-toggle')).toBeFocused()
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  await page.reload()
  await page.locator('.preview-settings-toggle').click()
  await expect(panel.locator('input[name="source-style-policy"]')).toHaveCount(0)
  await expect(panel.getByRole('button', { name: /^应用克莱因蓝主题/ })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => (await panel.boundingBox())!.width).toBeCloseTo(resizedWidth - 16, 0)
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await page.getByRole('navigation', { name: '手机工作区' }).getByRole('button', { name: '预览', exact: true }).click()
    await expect(panel).toBeVisible()
    await expect(panel.getByRole('tab', { name: '全部', exact: true })).toBeVisible()
    expect(await panel.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`wechat-inspector-${width}.png`), animations: 'disabled' })
  }
})

test('shares theme and style inspectors across all platforms and mobile sizes', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1674, height: 1000 })
  await page.goto('/')
  await page.getByRole('button', { name: '使用公众号长文模板开始' }).click()
  for (const [platform, panelId] of [['微信公众号', 'wechat-theme-panel'], ['小红书', 'xhs-tool-panel'], ['X 长文', 'x-formatting-panel']]) {
    await page.setViewportSize({ width: 1674, height: 1000 })
    await page.getByRole('tab', { name: platform, exact: true }).click()
    await page.locator('.preview-settings-toggle').click()
    const panel = page.locator(`#${panelId}`)
    const tabs = panel.locator('.inspector-tabs')
    await expect(tabs.getByRole('tab')).toHaveText(['主题', '样式'])
    await expect(panel.locator('input[name="source-style-policy"]')).toHaveCount(0)
    await expect.poll(async () => (await panel.boundingBox())!.width).toBe(310)
    await page.screenshot({ path: testInfo.outputPath(`${panelId}-themes.png`), animations: 'disabled' })
    await tabs.getByRole('tab', { name: '样式', exact: true }).click()
    await expect(panel.locator('.inspector-tab-panel:not([hidden])')).toHaveCount(1)
    await expect(panel.getByRole('radiogroup', { name: '选择文章字号' })).toBeVisible()
    await expect(panel.getByRole('radiogroup', { name: '选择文章行距' })).toBeVisible()
    if (platform === '小红书') {
      const palettes = panel.getByRole('radiogroup', { name: '选择小红书模板色板' })
      await palettes.getByRole('radio').nth(1).click()
      await expect(palettes.getByRole('radio').nth(1)).toHaveAttribute('aria-checked', 'true')
      await expect(panel.getByRole('checkbox', { name: '显示底部信息' })).toBeVisible()
      await panel.getByRole('textbox', { name: '左下角文字' }).fill('我的署名')
      await expect(page.locator('.xhs-card-page footer').first()).toContainText('我的署名')
    } else {
      await panel.getByRole('radio', { name: 'orange', exact: true }).click()
      await expect(panel.getByRole('radio', { name: 'orange', exact: true })).toHaveAttribute('aria-checked', 'true')
    }
    await page.screenshot({ path: testInfo.outputPath(`${panelId}-style.png`), animations: 'disabled' })
    const resize = page.locator('.preview-tool-resizer')
    expect(Math.abs((await resize.boundingBox())!.x + 10 - (await panel.boundingBox())!.x)).toBeLessThan(1)
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 })
      await page.getByRole('navigation', { name: '手机工作区' }).getByRole('button', { name: '预览', exact: true }).click()
      await expect(panel.getByRole('radio', { name: '宽松', exact: true })).toBeVisible()
      expect(await panel.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`${panelId}-${width}.png`), animations: 'disabled' })
    }
    await page.keyboard.press('Escape')
  }
})
