import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'
import { editTitle } from './workbench-helpers'

const gif = 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'

test('keeps decoded GIF/video nodes stable through unrelated controls and body edits', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.locator('input[accept*=".md"]').setInputFiles({ name: 'stable.md', mimeType: 'text/markdown', buffer: Buffer.from(`# 媒体稳定性\n\n正文内容。\n\n![动图](data:image/gif;base64,${gif})`) })
  const sample = readFileSync('e2e/video-upload.spec.ts', 'utf8').match(/const SAMPLE_WEBM = '([^']+)'/)![1]
  await page.locator('.cm-content').press('Control+End')
  await page.locator('input[accept=".mp4,.webm,video/mp4,video/webm"]').setInputFiles({ name: 'stable.webm', mimeType: 'video/webm', buffer: Buffer.from(sample, 'base64') })
  const media = page.locator('.wechat-content img')
  await expect(media).toHaveCount(2)
  for (const item of await media.all()) await expect(item).toHaveAttribute('src', /^blob:/)
  const originals = await media.elementHandles()
  const sources = await media.evaluateAll(nodes => nodes.map(node => node.getAttribute('src')))
  // Count any reassignments, even if the same cached URL is restored within a frame.
  await media.first().evaluate(() => {
    const state = { replacements: 0 }
    Object.assign(window, { __stableMedia: state })
    new MutationObserver(records => { state.replacements += records.filter(record => record.type === 'attributes' && record.attributeName === 'src').length })
      .observe(document.querySelector('.wechat-content')!, { subtree: true, attributes: true, attributeFilter: ['src'] })
  })
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('switch', { name: '同步滚动' }).uncheck()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '打开历史记录', exact: true }).click()
  await page.getByRole('button', { name: '打开历史记录', exact: true }).click()
  await page.locator('.preview-settings-toggle').click()
  await page.keyboard.press('Escape')
  await page.locator('.notification-trigger').click()
  await page.screenshot({ path: info.outputPath('notifications.png'), animations: 'disabled' })
  await page.getByRole('button', { name: '查看文档素材', exact: true }).click()
  await page.getByRole('button', { name: '正文', exact: true }).click()
  await editTitle(page, '修改后的媒体标题')
  await page.locator('.cm-content').press('Control+End')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('修改正文后，媒体仍保持原节点。')
  await page.locator('.topbar-document-title').click()
  await expect(page.locator('.wechat-content')).toContainText('修改正文后，媒体仍保持原节点。')
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  for (const original of originals) expect(await original.evaluate(node => node.isConnected)).toBe(true)
  expect(await media.evaluateAll(nodes => nodes.map(node => node.getAttribute('src')))).toEqual(sources)
  expect(await page.evaluate(() => (window as unknown as { __stableMedia: { replacements: number } }).__stableMedia.replacements)).toBe(0)
  expect(errors).toEqual([])
  await page.setViewportSize({ width: 320, height: 844 })
  await page.getByRole('navigation', { name: '手机工作区' }).getByRole('button', { name: '预览', exact: true }).click()
  await page.screenshot({ path: info.outputPath('mobile-preview.png'), animations: 'disabled' })
})

test('unifies new/import, preserves the draft on cancel and failure, and offers settings and help', async ({ page }, info) => {
  await page.goto('/')
  const create = page.getByRole('button', { name: '新建文档', exact: true })
  await create.click()
  await expect(page.getByRole('button', { name: '导入文件', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '空白文档', exact: true }).click()
  await editTitle(page, '正文里的标题')
  await page.locator('.cm-content').press('Control+End')
  await page.keyboard.insertText('这是正文。')
  await page.locator('.topbar-document-title').click()
  await expect(page.locator('.wechat-content')).toContainText('这是正文。')
  await expect(page.locator('.article-title-section')).toHaveCount(0)
  await create.click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.topbar-document-title')).toHaveText('正文里的标题')
  await create.click()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: '导入文件', exact: true }).click()
  await (await chooser).setFiles({ name: 'invalid.zip', mimeType: 'application/zip', buffer: Buffer.from('invalid') })
  await expect(page.getByRole('dialog', { name: '工作台通知' })).toContainText('ZIP')
  await expect(page.locator('.topbar-document-title')).toHaveText('正文里的标题')
  await expect(page.locator('.wechat-content')).toContainText('这是正文。')
  await page.getByRole('button', { name: '关闭通知' }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('switch', { name: '显示 Markdown 语法' }).check()
  await page.getByLabel('默认显示方式').selectOption('editor')
  await page.screenshot({ path: info.outputPath('settings.png') })
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.editor-grid')).toHaveClass(/workspace-mode-editor/)
  await expect(page.locator('.cm-content')).toContainText('# 正文里的标题')
  for (const name of ['模板素材库（规划中）', 'AI 工具（规划中）']) {
    await page.getByRole('button', { name, exact: true }).click()
    await expect(page.locator('.planned-feature')).toContainText('规划中')
    await page.keyboard.press('Escape')
  }
  await page.getByRole('button', { name: '帮助', exact: true }).click()
  const guide = page.getByRole('dialog', { name: '使用引导' })
  await expect(guide).toContainText('准备一篇稿件')
  await guide.getByRole('button', { name: '新建文档', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '新建文档', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(guide).toBeVisible()
  for (let step = 0; step < 5; step++) await guide.getByRole('button', { name: '下一步' }).click()
  await expect(guide).toContainText('同步到平台草稿箱')
  await guide.getByRole('button', { name: '打开发布面板', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '安装发布引擎' })).toBeVisible()
  await page.getByRole('button', { name: '继续本地编辑' }).click()
  await expect(guide).toContainText('同步到平台草稿箱')
  await guide.getByRole('button', { name: '下一步' }).click()
  await expect(guide).toContainText('前往平台复核')
  await guide.getByRole('button', { name: '完成', exact: true }).click()
  await expect(guide).toHaveCount(0)
})


test('inserts media below the title when the cursor is still in the title', async ({ page }) => {
  await page.goto('/')
  await page.locator('input[accept*=".md"]').setInputFiles({ name: 'title-media.md', mimeType: 'text/markdown', buffer: Buffer.from('# 保留文章标题\n\n原来的正文。') })
  await page.locator('.cm-content').press('Control+Home')
  await page.locator('.source-toolbar input[accept="image/*"]').setInputFiles({ name: 'test.gif', mimeType: 'image/gif', buffer: Buffer.from(gif, 'base64') })
  await expect(page.locator('.wechat-content img')).toHaveCount(1)
  await expect(page.locator('.topbar-document-title')).toHaveText('保留文章标题')
  await page.locator('.cm-content').press('Control+Home')
  const sample = readFileSync('e2e/video-upload.spec.ts', 'utf8').match(/const SAMPLE_WEBM = '([^']+)'/)![1]
  await page.locator('input[accept=".mp4,.webm,video/mp4,video/webm"]').setInputFiles({ name: 'title.webm', mimeType: 'video/webm', buffer: Buffer.from(sample, 'base64') })
  await expect(page.locator('.wechat-content img')).toHaveCount(2)
  await expect(page.locator('.topbar-document-title')).toHaveText('保留文章标题')
  await expect(page.locator('.wechat-content')).toContainText('原来的正文。')
  await expect(page.getByLabel('本地保存状态')).toHaveText('已保存')
  await page.reload()
  await expect(page.locator('.topbar-document-title')).toHaveText('保留文章标题')
  await expect(page.locator('.wechat-content img')).toHaveCount(2)
  await expect(page.locator('.wechat-document > h1')).toHaveCount(1)
  await expect(page.locator('.wechat-content h1')).toHaveCount(0)
})
